#!/usr/bin/env bash

set -eo pipefail
declare PROJLOC=..
declare HERE
HERE="$(dirname "$0")"

ex01() {

  echo "01 - Mocking auth"

  rm -rf proj-01 \
    && cp -a baseproj proj-01 \
    && cd "$_" \
    && tree

  cat << EOENV > .env
cds.requires.auth.kind=basic
cds.requires.auth.users.alan.roles=["admin","finance"]
EOENV

  cat << EOSERVICE > srv/main.cds
using northwhisper from '../db/schema';

@path    : '/northwhisper'
@requires: 'authenticated-user'
service Main {

  @restrict: [
    {
      grant: 'READ',
      to   : 'any'
    },
    {
      grant: 'WRITE',
      to   : 'finance'
    }
  ]
  entity Products   as projection on northwhisper.Products;

  entity Suppliers  as projection on northwhisper.Suppliers;
  entity Categories as projection on northwhisper.Categories;

}
EOSERVICE

}

ex02() {

  echo "02 - Mocking messaging"

  rm -rf proj-02 \
    && mkdir proj-02 \
    && cd "$_"

  cat << EOPACKAGEJSON > package.json
{
  "name": "messaging",
  "workspaces": [
    "*"
  ]
}
EOPACKAGEJSON

  # emitter

  cds init emitter --add nodejs,file-based-messaging

  cat << EOMAINCDS > emitter/srv/main.cds
namespace codejam.emitter;

@rest
service EmitterService {
  action greet(greeting: String) returns String;

  event Greeting.Received {
    info : String;
  }
}
EOMAINCDS

  cp "../$HERE/02/assets/emitter/srv/main.js" emitter/srv/
  cp "../$HERE/02/assets/emitter/index.cds" emitter/

  rm -rf emitter/{.gitignore,.vscode/,app/,db/,readme.md}

  # temp fix for cds 10 / ESM until 10.0.5
  sed --in-place 's/"type"/"_type"/' emitter/package.json

  # receiver

  cds init receiver --add nodejs,file-based-messaging
  rm -rf receiver/{.gitignore,.vscode/,app/,db/,srv/,readme.md}
  cp "../$HERE/02/assets/receiver/server.js" receiver/

  jq '.cds.requires["EmitterService"] = { service: "codejam.emitter.EmitterService", model: "emitter" }' receiver/package.json > /tmp/package.json \
    && cp /tmp/package.json receiver/

  # temp fix for cds 10 / ESM until 10.0.5
  sed --in-place 's/"type"/"_type"/' receiver/package.json

  npm install

}

ex05() {

  echo "05 - Exploring status-transition flows"

  rm -rf proj-05 \
    && mkdir proj-05 \
    && cd "$_"

  cat << EOSERVICES > services.cds
context codejam {

  type Position : String enum {
    Forward;
    Neutral;
    Reverse;
  }

  entity Controls {
    key ID       : Integer;
        position : Position default #Neutral;
  }
}

service Morse {

  entity Controls as projection on codejam.Controls

    actions {
      action engageForward();
      action engageNeutral();
      action engageReverse();
    };

}
EOSERVICES

  cat << EOANNOTATIONS >> services.cds

annotate Morse.Controls with @flow.status: position actions {
  engageForward  @from: #Neutral  @to: #Forward;
  engageNeutral  @from: [
    #Forward,
    #Reverse
  ]                               @to: #Neutral;
  engageReverse  @from: #Neutral  @to: #Reverse;
};
EOANNOTATIONS

}

ex08() {

  echo "08 - Discovering API client package export and reuse"

  rm -rf proj-08 \
    && mkdir proj-08 \
    && cd "$_"

  # Container

  cat << EOCONTAINERPACKAGEJSON > package.json
{
  "workspaces": [
    "*",
    "*/apis/*"
  ]
}
EOCONTAINERPACKAGEJSON

  # Producer

  cp -a ../baseproj northwhisper

  sed --in-place \
    's/"baseproj"/"northwhisper"/' \
    northwhisper/package.json

  cat << EOPRODUCTSUMMARY > northwhisper/srv/productsummary.cds
using northwhisper from '../db/schema';

@hcql  @odata
service ProductSummary {

  @readonly
  entity ProductData as
    projection on northwhisper.Products {
      ProductID                      as ID,
      ProductName                    as name,
      toupper(Category.CategoryName) as category : String,
      Supplier.CompanyName           as supplier
    }

}
EOPRODUCTSUMMARY

  pushd northwhisper \
    && cds export --data srv/productsummary.cds \
    && popd

  # Consumer

  mkdir consumer/ \
    && cd $_

  cat << EOCONSUMERPACKAGEJSON > package.json
{
  "name": "consumer",
  "version": "1.0.0",
  "type": "module",
  "description": "A simple consumer example project",
  "dependencies": {
    "@sap/cds": "^10"
  },
  "devDependencies": {
    "@cap-js/sqlite": "^3"
  },
  "scripts": {
    "start": "cds-serve"
  },
  "private": true
}
EOCONSUMERPACKAGEJSON

  sleep 0.1
  jq .name ../northwhisper/apis/productsummary/package.json
  npm add northwhisper-productsummary

  cat << EOSERVICES > services.cds
using from 'northwhisper-productsummary';
EOSERVICES

}

main() {

  local ex="${1:?Specify exercise number e.g. 01}"
  [[ "${#ex}" == 1 ]] && ex="0${ex}" # zero prefix
  cd "$HERE/$PROJLOC"
  "ex$ex"

}

main "$@"
